spring:
  application:
    name: receipt-processor

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
    com.hazelcast.instance: OFF
    com.hazelcast.core: OFF