version: '3.8'
services:
  eureka-server:
    build:
      context: .
      dockerfile: ./eureka-server/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
  loadbalancer:
    build:
      context: .
      dockerfile: ./loadbalancer/Dockerfile
    container_name: loadbalancer
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
  service3:
    build:
      context: .
      dockerfile: ./receipt-processor-service/Dockerfile
    container_name: receipt-processor-service
    ports:
      - "8081:8081"
    depends_on:
      - loadbalancer

# docker-compose build
# docker-compose up