spring:
  application:
    name: loadbalancer
  cloud:
    gateway:
      routes:
        - id: myRoute
          uri: lb://receipt-processor
          predicates:
            - Path=/receipts/**
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF